# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-13 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_content', models.CharField(max_length=8000)),
            ],
            options={
                'ordering': ['resource_id'],
                'permissions': (('view_resource', 'Can view resource'),),
            },
        ),
    ]
